spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:odmiana}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:secret}
wsjp:
  url: https://wsjp.pl
bot:
  owner_id: ${OWNER_ID}
  version: ${VERSION:0.0.0}
