spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:odmiana}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:secret}
sjp:
  url: https://sjp.pl
wikislownik:
  url: https://pl.wiktionary.org/w/api.php?action=parse&format=json&prop=text|categories&page=
bot:
  owner_id: ${OWNER_ID}
  version: ${VERSION:0.0.0}
